// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Field = require("./field.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var View$BsReactNative = require("bs-react-native/lib/js/src/components/view.js");
var Style$BsReactNative = require("bs-react-native/lib/js/src/style.js");
var SafeAreaView$BsReactNative = require("bs-react-native/lib/js/src/components/safeAreaView.js");

function app() {
  return ReasonReact.element(/* None */0, /* None */0, View$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[Style$BsReactNative.style(/* :: */[
                          Style$BsReactNative.flex(1),
                          /* :: */[
                            Style$BsReactNative.justifyContent(/* Center */2),
                            /* :: */[
                              Style$BsReactNative.alignItems(/* Center */2),
                              /* :: */[
                                Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["black"])),
                                /* [] */0
                              ]
                            ]
                          ]
                        ])], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[ReasonReact.element(/* None */0, /* None */0, Curry.app(SafeAreaView$BsReactNative.make, [
                            /* None */0,
                            /* None */0,
                            /* None */0,
                            /* None */0,
                            /* None */0,
                            /* None */0,
                            /* None */0,
                            /* None */0,
                            /* None */0,
                            /* None */0,
                            /* None */0,
                            /* None */0,
                            /* None */0,
                            /* None */0,
                            /* None */0,
                            /* None */0,
                            /* None */0,
                            /* None */0,
                            /* None */0,
                            /* None */0,
                            /* array */[ReasonReact.element(/* None */0, /* None */0, Field.make(/* array */[]))]
                          ]))]));
}

exports.app = app;
/* Field Not a pure module */
