// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");
var View$BsReactNative = require("bs-react-native/lib/js/src/components/view.js");
var Style$BsReactNative = require("bs-react-native/lib/js/src/style.js");
var RNEvent$BsReactNative = require("bs-react-native/lib/js/src/RNEvent.js");
var Dimensions$BsReactNative = require("bs-react-native/lib/js/src/dimensions.js");

var Stupid = Caml_exceptions.create("FieldTouchHandler.Stupid");

var windowWidth = Dimensions$BsReactNative.get(/* window */-762539024).width;

var pieceWidth = windowWidth / 10;

function coord(e) {
  return /* tuple */[
          RNEvent$BsReactNative.TouchEvent[/* pageX */4](e),
          RNEvent$BsReactNative.TouchEvent[/* pageY */5](e)
        ];
}

var component = ReasonReact.reducerComponent("FieldTouchHandler");

function make(moveX, rotate, moveY, children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, /* record */[
                                /* onMoveShouldSetResponder */(function () {
                                    console.log("onMoveShouldSetResponder");
                                    return true;
                                  }),
                                /* onMoveShouldSetResponderCapture */(function () {
                                    return true;
                                  }),
                                /* onResponderGrant */(function (e) {
                                    return Curry._1(self[/* send */3], /* Start */Block.__(1, [coord(e)]));
                                  }),
                                /* onResponderMove */(function (e) {
                                    return Curry._1(self[/* send */3], /* Move */Block.__(0, [coord(e)]));
                                  }),
                                /* onResponderReject */(function () {
                                    console.log("reject");
                                    return /* () */0;
                                  }),
                                /* onResponderRelease */(function (e) {
                                    return Curry._1(self[/* send */3], /* End */Block.__(2, [coord(e)]));
                                  }),
                                /* onResponderTerminate */(function () {
                                    console.log("terminate");
                                    return /* () */0;
                                  }),
                                /* onResponderTerminationRequest */(function () {
                                    console.log("terminationrequest");
                                    return /* () */0;
                                  }),
                                /* onStartShouldSetResponder */(function () {
                                    return true;
                                  }),
                                /* onStartShouldSetResponderCapture */(function () {
                                    return true;
                                  })
                              ], undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                        Style$BsReactNative.position(/* Relative */1),
                                        /* :: */[
                                          Style$BsReactNative.display(/* Flex */0),
                                          /* :: */[
                                            Style$BsReactNative.flex(1),
                                            /* [] */0
                                          ]
                                        ]
                                      ])), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(children));
            }),
          /* initialState */(function () {
              return /* record */[
                      /* start */undefined,
                      /* lastMoveCoord */undefined,
                      /* pos */undefined
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              switch (action.tag | 0) {
                case 0 : 
                    var thisCoord = action[0];
                    var yNow = thisCoord[1];
                    var xNow = thisCoord[0];
                    console.log("thisCoord", thisCoord);
                    var match = state[/* start */0];
                    var start;
                    if (match !== undefined) {
                      start = match;
                    } else {
                      throw [
                            Stupid,
                            "Start should really be set here"
                          ];
                    }
                    var match$1 = Math.abs(start[0] - xNow) - Math.abs(start[1] - yNow) > 0;
                    var dir = match$1 ? /* X */0 : /* Y */1;
                    var match$2 = state[/* lastMoveCoord */1];
                    var match$3 = match$2 !== undefined ? match$2 : start;
                    var yLastMove = match$3[1];
                    var xLastMove = match$3[0];
                    var updateCoord = function () {
                      return /* Update */Block.__(0, [/* record */[
                                  /* start */state[/* start */0],
                                  /* lastMoveCoord */thisCoord,
                                  /* pos */state[/* pos */2]
                                ]]);
                    };
                    if (dir) {
                      var match$4 = yLastMove - yNow > pieceWidth && state[/* lastMoveCoord */1] === undefined;
                      if (match$4) {
                        Curry._1(rotate, /* () */0);
                        return updateCoord(/* () */0);
                      } else {
                        var match$5 = yLastMove - yNow < -pieceWidth;
                        if (match$5) {
                          Curry._1(moveY, /* () */0);
                          return updateCoord(/* () */0);
                        } else {
                          return /* NoUpdate */0;
                        }
                      }
                    } else {
                      var match$6 = xLastMove - xNow > pieceWidth / 1.5;
                      if (match$6) {
                        Curry._1(moveX, /* Left */0);
                        return updateCoord(/* () */0);
                      } else {
                        var match$7 = xLastMove - xNow < -pieceWidth;
                        if (match$7) {
                          Curry._1(moveX, /* Right */1);
                          return updateCoord(/* () */0);
                        } else {
                          return /* NoUpdate */0;
                        }
                      }
                    }
                case 1 : 
                    return /* Update */Block.__(0, [/* record */[
                                /* start */action[0],
                                /* lastMoveCoord */state[/* lastMoveCoord */1],
                                /* pos */state[/* pos */2]
                              ]]);
                case 2 : 
                    return /* Update */Block.__(0, [/* record */[
                                /* start */undefined,
                                /* lastMoveCoord */undefined,
                                /* pos */state[/* pos */2]
                              ]]);
                
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.Stupid = Stupid;
exports.windowWidth = windowWidth;
exports.pieceWidth = pieceWidth;
exports.coord = coord;
exports.component = component;
exports.make = make;
/* windowWidth Not a pure module */
