// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var View$BsReactNative = require("bs-react-native/lib/js/src/components/view.js");
var Style$BsReactNative = require("bs-react-native/lib/js/src/style.js");

var component = ReasonReact.statelessComponent("Pixel");

function make(pos, bgColor, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                        Style$BsReactNative.position(/* Absolute */0),
                                        /* :: */[
                                          Style$BsReactNative.bottom(/* Pct */Block.__(1, [Caml_int32.imul(5, pos[1])])),
                                          /* :: */[
                                            Style$BsReactNative.left(/* Pct */Block.__(1, [Caml_int32.imul(10, pos[0])])),
                                            /* :: */[
                                              Style$BsReactNative.width(/* Pct */Block.__(1, [10])),
                                              /* :: */[
                                                Style$BsReactNative.height(/* Pct */Block.__(1, [5])),
                                                /* :: */[
                                                  Style$BsReactNative.backgroundColor(/* String */Block.__(0, [bgColor])),
                                                  /* :: */[
                                                    Style$BsReactNative.borderColor(/* String */Block.__(0, ["rgb(40, 40, 40)"])),
                                                    /* :: */[
                                                      Style$BsReactNative.borderWidth(1),
                                                      /* :: */[
                                                        Style$BsReactNative.borderStyle(/* Solid */0),
                                                        /* [] */0
                                                      ]
                                                    ]
                                                  ]
                                                ]
                                              ]
                                            ]
                                          ]
                                        ]
                                      ])), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
